[package]
name = "git-rs"
version = "0.1.0"
authors = ["Krouton <krouton@hatena.ne.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libflate = "1"
rust-crypto = "0.2.36"
clap = "3.0.0-beta.2"
